name: testainers
description: Testainers is a powerful Dart plugin designed to streamline the management of containers for testing purposes.
version: 0.3.0
repository: https://github.com/testainers/testainers
homepage: https://testainers.testainers.com/

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.15.0

  # https://pub.dev/packages/dartssh2
  dartssh2: ^2.13.0

  # https://pub.dev/packages/http
  http: ^1.6.0

  # https://pub.dev/packages/lints
  lints: ^6.0.0

  # https://pub.dev/packages/markdown
  markdown: ^7.3.0

  # https://pub.dev/packages/mongo_dart
  mongo_dart: ^0.10.0

  # https://pub.dev/packages/postgres
  postgres: ^3.5.0

  # https://pub.dev/packages/redis
  redis: ^4.0.0

  # https://pub.dev/packages/test
  test: ^1.29.0
